### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by jiejiezhang** [yuwei-wu/kr_param_map#3]
In file included from /opt/ros/melodic/include/roslz4/lz4s.h:38,
                 from /opt/ros/melodic/include/rosbag/stream.h:46,
                 from /opt/ros/melodic/include/rosbag/chunked_file.h:46,
                 from /opt/ros/melodic/include/rosbag/bag.h:41,
                 from /home/jason/code/path/kr_param_map_ws/src/kr_param_map/param_env/src/read_grid_map.cpp:11:
/usr/include/lz4.h:196:57: error: conflicting declaration ‘typedef struct LZ4_stream_t LZ4_stream_t’
  196 | typedef struct { long long table[LZ4_STREAMSIZE_U64]; } LZ4_stream_t;
      |                                                         ^~~~~~~~~~~~
In file included from /usr/include/flann/util/serialization.h:9,
                 from /usr/include/flann/util/matrix.h:35,
                 from /usr/include/flann/flann.hpp:41,
                 from /usr/include/pcl-1.8/pcl/kdtree/flann.h:50,
                 from /usr/include/pcl-1.8/pcl/kdtree/kdtree_flann.h:45,
                 from /home/jason/code/path/kr_param_map_ws/src/kr_param_map/param_env/src/read_grid_map.cpp:5:
/usr/include/flann/ext/lz4.h:196:57: note: previous declaration as ‘typedef struct LZ4_stream_t LZ4_stream_t’
  196 | typedef struct { long long table[LZ4_STREAMSIZE_U64]; } LZ4_stream_t;
      |                                                         ^~~~~~~~~~~~
In file included from /opt/ros/melodic/include/roslz4/lz4s.h:38,
                 from /opt/ros/melodic/include/rosbag/stream.h:46,
                 from /opt/ros/melodic/include/rosbag/chunked_file.h:46,
                 from /opt/ros/melodic/include/rosbag/bag.h:41,
                 from /home/jason/code/path/kr_param_map_ws/src/kr_param_map/param_env/src/read_grid_map.cpp:11:
/usr/include/lz4.h:249:72: error: conflicting declaration ‘typedef struct LZ4_streamDecode_t LZ4_streamDecode_t’
  249 | typedef struct { unsigned long long table[LZ4_STREAMDECODESIZE_U64]; } LZ4_streamDecode_t;
      |                                                                        ^~~~~~~~~~~~~~~~~~
In file included from /usr/include/flann/util/serialization.h:9,
                 from /usr/include/flann/util/matrix.h:35,
                 from /usr/include/flann/flann.hpp:41,
                 from /usr/include/pcl-1.8/pcl/kdtree/flann.h:50,
                 from /usr/include/pcl-1.8/pcl/kdtree/kdtree_flann.h:45,
                 from /home/jason/code/path/kr_param_map_ws/src/kr_param_map/param_env/src/read_grid_map.cpp:5:
/usr/include/flann/ext/lz4.h:249:72: note: previous declaration as ‘typedef struct LZ4_streamDecode_t LZ4_streamDecode_t’
  249 | typedef struct { unsigned long long table[LZ4_STREAMDECODESIZE_U64]; } LZ4_streamDecode_t;
      |                                                                        ^~~~~~~~~~~~~~~~~~

**Comment by yuwei-wu** [comment]
Hi, it looks like a dependency issue, could you elaborate more about your versions of dependencies?

**Comment by Abner0907** [comment]
you can try this:
> sudo mv /usr/include/flann/ext/lz4.h /usr/include/flann/ext/lz4.h.bak
sudo mv /usr/include/flann/ext/lz4hc.h /usr/include/flann/ext/lz4.hc.bak
sudo ln -s /usr/include/lz4.h /usr/include/flann/ext/lz4.h
sudo ln -s /usr/include/lz4hc.h /usr/include/flann/ext/lz4hc.h
